// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nRoBhVUYSpHsuIehFTUKzU0IOoHckpw',
    appId: '1:844229422024:web:72de920e429b2c16eeeefd',
    messagingSenderId: '844229422024',
    projectId: 'schoolmanagementsystem-43845',
    authDomain: 'schoolmanagementsystem-43845.firebaseapp.com',
    storageBucket: 'schoolmanagementsystem-43845.appspot.com',
    measurementId: 'G-XFKEVWPZFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uKWCiE9gefwpPbm8osVb8Wj7aBD1eFc',
    appId: '1:844229422024:android:536dee8008b8c8deeeeefd',
    messagingSenderId: '844229422024',
    projectId: 'schoolmanagementsystem-43845',
    storageBucket: 'schoolmanagementsystem-43845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6CpwkhCwqr7EoEbIkI7GuTfKZawDvX0',
    appId: '1:844229422024:ios:ec4b0bd89ed3a080eeeefd',
    messagingSenderId: '844229422024',
    projectId: 'schoolmanagementsystem-43845',
    storageBucket: 'schoolmanagementsystem-43845.appspot.com',
    iosClientId: '844229422024-bb88ch06rl6lphrdjmjcbmogne7pgmjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSchoolManagementAdminPanel',
  );
}
